# Generated by Django 5.1 on 2024-08-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_user_alter_vote_employee_delete_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Employee',
        ),
    ]
